name: Flutter CI/CD with Firebase Distribution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_distribute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Release)
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # ✅ Create .env dynamically from GitHub Secrets
      - name: Create .env file for Fastlane
        run: |
          echo "APP_ID=${{ secrets.APP_ID }}" >> android/.env
          echo "FIREBASE_CLI_TOKEN=${{ secrets.FIREBASE_CLI_TOKEN }}" >> android/.env

      # ✅ Run Fastlane inside android directory
      - name: Run Fastlane (Firebase Distribution)
        run: |
          cd android
          bundle install
          bundle exec fastlane fastlane_app_distribution

      # # ✅ Optional: Direct Firebase upload (if not handled by Fastlane)
      # - name: Upload APK Artifact to Firebase App Distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{ secrets.APP_ID }}
      #     serviceCredentialsFileContent: ${{ secrets.GOOGLE_APPLICATION_CREDENTIAL }}
      #     groups: testers
      #     file: build/app/outputs/flutter-apk/app-release.apk
