name: Flutter CI/CD with Firebase Distribution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_distribute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Release)
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk



            # ✅ Upload directly to Firebase App Distribution
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.GOOGLE_SERVICE_CREIDINTIAL }}
          groups: "mariamattef656@gmail.com,mariamatte2024@gmail.com"
          file: build/app/outputs/flutter-apk/app-release.apk
          releaseNotes: "Automated release from GitHub Actions"

      # # ✅ Create .env dynamically from GitHub Secrets
      # - name: Create .env file for Fastlane
      #   run: |
      #     echo "APP_ID=${{ secrets.APP_ID }}" >> android/.env
      #     echo "FIREBASE_CLI_TOKEN=${{ secrets.FIREBASE_CLI_TOKEN }}" >> android/.env

      # # ✅ Set up Ruby environment (recommended way)
      # - name: Setup Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: "3.4.7"
      #     bundler-cache: true
      #     working-directory: android

      # # ✅ Run Fastlane inside android directory
      # - name: Run Fastlane (Firebase Distribution)
      #   run: |
      #     cd android
      #     bundle install
          # bundle exec fastlane fastlane_app_distribution
